# alert_system.py - Alert system for critical events in FluentSignalCopier

# Licensed under the Attribution-NonCommercial-ShareAlike 4.0 International
# See LICENSE.txt for terms. No warranty; use at your own risk.
# Copyright (c) 2025 R4V3N. All rights reserved.

import json
import time
import smtplib
import asyncio
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List, Any, Optional, Callable
from dataclasses import dataclass, field
from email.mime.text import MimeText
from email.mime.multipart import MimeMultipart
import logging
import threading
from enum import Enum

class AlertLevel(Enum):
    """Alert severity levels"""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"

@dataclass
class AlertRule:
    """Definition of an alert rule"""
    name: str
    condition: Callable[[Dict[str, Any]], bool]
    level: AlertLevel
    message_template: str
    cooldown_minutes: int = 5
    enabled: bool = True
    last_triggered: Optional[datetime] = None
    
    def can_trigger(self) -> bool:
        """Check if enough time has passed since last trigger"""
        if not self.enabled:
            return False
        if self.last_triggered is None:
            return True
        return datetime.now() - self.last_triggered > timedelta(minutes=self.cooldown_minutes)
    
    def trigger(self) -> None:
        """Mark rule as triggered"""
        self.last_triggered = datetime.now()

@dataclass
class Alert:
    """An individual alert instance"""
    rule_name: str
    level: AlertLevel
    message: str
    timestamp: datetime = field(default_factory=datetime.now)
    data: Dict[str, Any] = field(default_factory=dict)
    acknowledged: bool = False

class EmailNotifier:
    """Email notification handler"""
    
    def __init__(self, smtp_server: str, smtp_port: int, username: str, password: str, 
                 from_email: str, to_emails: List[str]):
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.username = username
        self.password = password
        self.from_email = from_email
        self.to_emails = to_emails
        self.enabled = True
        
    async def send_alert(self, alert: Alert) -> bool:
        """Send alert via email"""
        if not self.enabled:
            return False
            
        try:
            msg = MimeMultipart()
            msg['From'] = self.from_email
            msg['To'] = ', '.join(self.to_emails)
            msg['Subject'] = f"[{alert.level.value.upper()}] FluentSignalCopier - {alert.rule_name}"
            
            body = self._format_email_body(alert)
            msg.attach(MimeText(body, 'html'))
            
            # Send email in thread to avoid blocking
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(None, self._send_email_sync, msg)
            return True
            
        except Exception as e:
            logging.error(f"Failed to send email alert: {e}")
            return False
    
    def _send_email_sync(self, msg: MimeMultipart):
        """Synchronous email sending"""
        with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
            server.starttls()
            server.login(self.username, self.password)
            server.send_message(msg)
    
    def _format_email_body(self, alert: Alert) -> str:
        """Format email body with HTML"""
        color_map = {
            AlertLevel.INFO: "#17a2b8",
            AlertLevel.WARNING: "#ffc107", 
            AlertLevel.ERROR: "#dc3545",
            AlertLevel.CRITICAL: "#6f42c1"
        }
        
        color = color_map.get(alert.level, "#6c757d")
        
        html = f"""
        <html>
        <body style="font-family: Arial, sans-serif;">
            <div style="border-left: 4px solid {color}; padding: 20px; margin: 20px 0;">
                <h2 style="color: {color}; margin-top: 0;">
                    {alert.level.value.upper()}: {alert.rule_name}
                </h2>
                <p><strong>Time:</strong> {alert.timestamp.strftime('%Y-%m-%d %H:%M:%S')}</p>
                <p><strong>Message:</strong> {alert.message}</p>
                
                {self._format_alert_data(alert.data)}
                
                <hr style="margin: 20px 0;">
                <p style="color: #6c757d; font-size: 12px;">
                    This alert was generated by FluentSignalCopier monitoring system.
                </p>
            </div>
        </body>
        </html>
        """
        return html
    
    def _format_alert_data(self, data: Dict[str, Any]) -> str:
        """Format additional alert data"""
        if not data:
            return ""
        
        html = "<h4>Additional Information:</h4><ul>"
        for key, value in data.items():
            html += f"<li><strong>{key}:</strong> {value}</li>"
        html += "</ul>"
        return html

class WebhookNotifier:
    """Webhook notification handler (for Slack, Discord, etc.)"""
    
    def __init__(self, webhook_url: str, webhook_type: str = "slack"):
        self.webhook_url = webhook_url
        self.webhook_type = webhook_type.lower()
        self.enabled = True
    
    async def send_alert(self, alert: Alert) -> bool:
        """Send alert via webhook"""
        if not self.enabled:
            return False
            
        try:
            import aiohttp
            
            payload = self._format_webhook_payload(alert)
            
            async with aiohttp.ClientSession() as session:
                async with session.post(self.webhook_url, json=payload) as response:
                    return response.status == 200
                    
        except ImportError:
            logging.error("aiohttp not installed - cannot send webhook alerts")
            return False
        except Exception as e:
            logging.error(f"Failed to send webhook alert: {e}")
            return False
    
    def _format_webhook_payload(self, alert: Alert) -> Dict[str, Any]:
        """Format webhook payload based on type"""
        if self.webhook_type == "slack":
            return self._format_slack_payload(alert)
        elif self.webhook_type == "discord":
            return self._format_discord_payload(alert)
        else:
            # Generic webhook format
            return {
                "alert": {
                    "rule": alert.rule_name,
                    "level": alert.level.value,
                    "message": alert.message,
                    "timestamp": alert.timestamp.isoformat(),
                    "data": alert.data
                }
            }
    
    def _format_slack_payload(self, alert: Alert) -> Dict[str, Any]:
        """Format Slack webhook payload"""
        color_map = {
            AlertLevel.INFO: "good",
            AlertLevel.WARNING: "warning",
            AlertLevel.ERROR: "danger", 
            AlertLevel.CRITICAL: "#6f42c1"
        }
        
        color = color_map.get(alert.level, "#6c757d")
        
        fields = []
        for key, value in alert.data.items():
            fields.append({
                "title": key,
                "value": str(value),
                "short": True
            })
        
        return {
            "attachments": [{
                "color": color,
                "title": f"{alert.level.value.upper()}: {alert.rule_name}",
                "text": alert.message,
                "timestamp": int(alert.timestamp.timestamp()),
                "fields": fields,
                "footer": "FluentSignalCopier"
            }]
        }
    
    def _format_discord_payload(self, alert: Alert) -> Dict[str, Any]:
        """Format Discord webhook payload"""
        color_map = {
            AlertLevel.INFO: 0x17a2b8,
            AlertLevel.WARNING: 0xffc107,
            AlertLevel.ERROR: 0xdc3545,
            AlertLevel.CRITICAL: 0x6f42c1
        }
        
        color = color_map.get(alert.level, 0x6c757d)
        
        fields = []
        for key, value in alert.data.items():
            fields.append({
                "name": key,
                "value": str(value),
                "inline": True
            })
        
        return {
            "embeds": [{
                "title": f"{alert.level.value.upper()}: {alert.rule_name}",
                "description": alert.message,
                "color": color,
                "timestamp": alert.timestamp.isoformat(),
                "fields": fields,
                "footer": {
                    "text": "FluentSignalCopier"
                }
            }]
        }

class AlertManager:
    """Main alert management system"""
    
    def __init__(self, log_dir: str = "logs"):
        self.log_dir = Path(log_dir)
        self.rules: List[AlertRule] = []
        self.alerts: List[Alert] = []
        self.notifiers = []
        self.running = False
        self.max_alerts_history = 1000
        
        # Setup default rules
        self._setup_default_rules()
        
        # File monitoring
        self.file_positions = {}
        self.last_heartbeat_check = datetime.now()
    
    def add_notifier(self, notifier):
        """Add a notification handler"""
        self.notifiers.append(notifier)
    
    def add_rule(self, rule: AlertRule):
        """Add an alert rule"""
        self.rules.append(rule)
    
    def _setup_default_rules(self):
        """Setup default alert rules"""
        # Critical: System heartbeat is dead
        self.add_rule(AlertRule(
            name="Heartbeat Dead",
            condition=lambda data: self._check_heartbeat_dead(data),
            level=AlertLevel.CRITICAL,
            message_template="System heartbeat has been dead for over 5 minutes",
            cooldown_minutes=15
        ))
        
        # Error: High error rate
        self.add_rule(AlertRule(
            name="High Error Rate",
            condition=lambda data: self._check_high_error_rate(data),
            level=AlertLevel.ERROR,
            message_template="High error rate detected: {error_count} errors in last 10 minutes",
            cooldown_minutes=10
        ))
        
        # Warning: No signals for extended period
        self.add_rule(AlertRule(
            name="No Signal Activity",
            condition=lambda data: self._check_no_signal_activity(data),
            level=AlertLevel.WARNING,
            message_template="No signal activity for over 2 hours",
            cooldown_minutes=60
        ))
        
        # Critical: Emergency close triggered
        self.add_rule(AlertRule(
            name="Emergency Close",
            condition=lambda data: self._check_emergency_close(data),
            level=AlertLevel.CRITICAL,
            message_template="Emergency close all positions triggered",
            cooldown_minutes=1
        ))
        
        # Error: Trade execution failures
        self.add_rule(AlertRule(
            name="Trade Execution Failures",
            condition=lambda data: self._check_trade_failures(data),
            level=AlertLevel.ERROR,
            message_template="Multiple trade execution failures detected",
            cooldown_minutes=5
        ))
        
        # Warning: Connection issues
        self.add_rule(AlertRule(
            name="Connection Issues",
            condition=lambda data: self._check_connection_issues(data),
            level=AlertLevel.WARNING,
            message_template="Telegram connection issues detected",
            cooldown_minutes=10
        ))
    
    def _check_heartbeat_dead(self, data: Dict[str, Any]) -> bool:
        """Check if heartbeat is dead"""
        heartbeat_files = list(self.log_dir.parent.glob("**/fluent_heartbeat.txt"))
        if not heartbeat_files:
            return True
        
        try:
            latest_heartbeat = max(heartbeat_files, key=lambda f: f.stat().st_mtime)
            with open(latest_heartbeat, 'r') as f:
                timestamp_str = f.read().strip()
            
            if timestamp_str.isdigit():
                heartbeat_time = datetime.fromtimestamp(int(timestamp_str))
                age = datetime.now() - heartbeat_time
                return age.total_seconds() > 300  # 5 minutes
        except Exception:
            return True
        
        return False
    
    def _check_high_error_rate(self, data: Dict[str, Any]) -> bool:
        """Check for high error rate"""
        # This would analyze recent log entries for error patterns
        # Simplified implementation
        recent_errors = data.get('recent_error_count', 0)
        return recent_errors > 10
    
    def _check_no_signal_activity(self, data: Dict[str, Any]) -> bool:
        """Check for lack of signal activity"""
        last_signal_time = data.get('last_signal_time')
        if not last_signal_time:
            return True
        
        try:
            last_time = datetime.fromisoformat(last_signal_time)
            age = datetime.now() - last_time
            return age.total_seconds() > 7200  # 2 hours
        except Exception:
            return False
    
    def _check_emergency_close(self, data: Dict[str, Any]) -> bool:
        """Check for emergency close events"""
        return data.get('emergency_close_triggered', False)
    
    def _check_trade_failures(self, data: Dict[str, Any]) -> bool:
        """Check for trade execution failures"""
        failed_trades = data.get('failed_trades_count', 0)
        return failed_trades > 3
    
    def _check_connection_issues(self, data: Dict[str, Any]) -> bool:
        """Check for connection issues"""
        connection_errors = data.get('connection_errors', 0)
        return connection_errors > 5
    
    async def process_log_entry(self, log_entry: Dict[str, Any]):
        """Process a single log entry for alerts"""
        # Extract relevant data for rule evaluation
        evaluation_data = self._extract_evaluation_data(log_entry)
        
        # Check each rule
        for rule in self.rules:
            if rule.can_trigger() and rule.condition(evaluation_data):
                alert = Alert(
                    rule_name=rule.name,
                    level=rule.level,
                    message=rule.message_template.format(**evaluation_data),
                    data=evaluation_data
                )
                
                await self._fire_alert(alert)
                rule.trigger()
    
    def _extract_evaluation_data(self, log_entry: Dict[str, Any]) -> Dict[str, Any]:
        """Extract data needed for rule evaluation"""
        # This would analyze recent logs and extract metrics
        # Simplified implementation
        return {
            'recent_error_count': 0,
            'last_signal_time': log_entry.get('timestamp'),
            'emergency_close_triggered': 'EMERGENCY_CLOSE_ALL' in log_entry.get('message', ''),
            'failed_trades_count': 0,
            'connection_errors': 0
        }
    
    async def _fire_alert(self, alert: Alert):
        """Fire an alert to all notifiers"""
        self.alerts.append(alert)
        
        # Keep alerts history bounded
        if len(self.alerts) > self.max_alerts_history:
            self.alerts = self.alerts[-self.max_alerts_history:]
        
        # Send to all notifiers
        for notifier in self.notifiers:
            try:
                await notifier.send_alert(alert)
            except Exception as e:
                logging.error(f"Failed to send alert via {type(notifier).__name__}: {e}")
        
        # Log the alert
        logging.warning(f"ALERT [{alert.level.value}] {alert.rule_name}: {alert.message}")
    
    async def start_monitoring(self, check_interval: int = 30):
        """Start the alert monitoring loop"""
        self.running = True
        logging.info("Alert monitoring started")
        
        while self.running:
            try:
                await self._check_alerts()
                await asyncio.sleep(check_interval)
            except Exception as e:
                logging.error(f"Error in alert monitoring: {e}")
                await asyncio.sleep(check_interval)
    
    async def _check_alerts(self):
        """Check for alert conditions"""
        # Read recent log entries
        log_files = list(self.log_dir.glob("*.log"))
        
        for log_file in log_files:
            await self._process_log_file(log_file)
    
    async def _process_log_file(self, log_file: Path):
        """Process a log file for alerts"""
        try:
            current_pos = self.file_positions.get(str(log_file), 0)
            
            with open(log_file, 'r', encoding='utf-8') as f:
                f.seek(current_pos)
                new_lines = f.readlines()
                self.file_positions[str(log_file)] = f.tell()
            
            for line in new_lines:
                if line.strip():
                    try:
                        log_entry = json.loads(line.strip())
                        await self.process_log_entry(log_entry)
                    except json.JSONDecodeError:
                        # Handle non-JSON lines
                        log_entry = {
                            'timestamp': datetime.now().isoformat(),
                            'message': line.strip(),
                            'level': 'INFO'
                        }
                        await self.process_log_entry(log_entry)
                        
        except Exception as e:
            logging.error(f"Error processing log file {log_file}: {e}")
    
    def stop_monitoring(self):
        """Stop the alert monitoring"""
        self.running = False
        logging.info("Alert monitoring stopped")
    
    def get_alert_summary(self) -> Dict[str, Any]:
        """Get summary of recent alerts"""
        now = datetime.now()
        recent_alerts = [a for a in self.alerts if now - a.timestamp < timedelta(hours=24)]
        
        return {
            'total_alerts_24h': len(recent_alerts),
            'critical_alerts_24h': len([a for a in recent_alerts if a.level == AlertLevel.CRITICAL]),
            'error_alerts_24h': len([a for a in recent_alerts if a.level == AlertLevel.ERROR]),
            'warning_alerts_24h': len([a for a in recent_alerts if a.level == AlertLevel.WARNING]),
            'last_alert': recent_alerts[-1].timestamp.isoformat() if recent_alerts else None,
            'active_rules': len([r for r in self.rules if r.enabled]),
            'total_rules': len(self.rules)
        }

# Configuration helper
def load_alert_config(config_file: str = "alert_config.json") -> Dict[str, Any]:
    """Load alert configuration from file"""
    config_path = Path(config_file)
    if config_path.exists():
        with open(config_path, 'r') as f:
            return json.load(f)
    
    # Default configuration
    default_config = {
        "email": {
            "enabled": False,
            "smtp_server": "smtp.gmail.com",
            "smtp_port": 587,
            "username": "",
            "password": "",
            "from_email": "",
            "to_emails": []
        },
        "webhook": {
            "enabled": False,
            "webhook_url": "",
            "webhook_type": "slack"
        },
        "monitoring": {
            "check_interval": 30,
            "log_dir": "logs"
        }
    }
    
    # Save default config
    with open(config_path, 'w') as f:
        json.dump(default_config, f, indent=2)
    
    return default_config

async def main():
    """Main entry point for alert system"""
    config = load_alert_config()
    
    # Setup logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Create alert manager
    alert_manager = AlertManager(config['monitoring']['log_dir'])
    
    # Setup email notifier if configured
    if config['email']['enabled']:
        email_notifier = EmailNotifier(
            smtp_server=config['email']['smtp_server'],
            smtp_port=config['email']['smtp_port'],
            username=config['email']['username'],
            password=config['email']['password'],
            from_email=config['email']['from_email'],
            to_emails=config['email']['to_emails']
        )
        alert_manager.add_notifier(email_notifier)
    
    # Setup webhook notifier if configured
    if config['webhook']['enabled']:
        webhook_notifier = WebhookNotifier(
            webhook_url=config['webhook']['webhook_url'],
            webhook_type=config['webhook']['webhook_type']
        )
        alert_manager.add_notifier(webhook_notifier)
    
    # Start monitoring
    try:
        await alert_manager.start_monitoring(config['monitoring']['check_interval'])
    except KeyboardInterrupt:
        logging.info("Alert system stopped by user")
    finally:
        alert_manager.stop_monitoring()

if __name__ == "__main__":
    asyncio.run(main())